export const FIRST_IMG_INFO = 'FIRST_IMG_INFO';
export const SECOND_IMG_INFO = 'SECOND_IMG_INFO';
export const THIRD_IMG_INFO = 'THIRD_IMG_INFO';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';